spring:
  datasource:
    url: jdbc:postgresql://localhost:5331/test_2
    username: kachepasimon
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
